name: Update README.md

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v2
    - run: |
        python build.py
        git config --global user.name 'Brian'
        git config --global user.email 'bmc@shmoo.com'
        git commit -am "update README.md" || true
        git push
